### ISSUE TITLE
Separate Attributes into another project

### ISSUE THREAD

**Issue by holmes-mike** [domn1995/dunet#147]
Create a separate project with Attributes explicitly defined in code and referenced by the source generator.

This will help to avoid conflicts that generating the attribute current cause and the Attribute will be more easily discoverable.

An example in which the attributes are in a separate project from the source generator (and also not source generated in the project consuming the library)
https://github.com/CommunityToolkit/dotnet/tree/main/src/CommunityToolkit.Mvvm/ComponentModel/Attributes

Example where Attribute can't be discovered
![image](https://github.com/domn1995/dunet/assets/56387624/7a29f61c-9ef3-43d6-9974-2c1e027a965b)

**Comment by hwoodiwiss** [comment]
There's an MSBuild target package that someone has created that does this well
https://github.com/ViktorHofer/PackAsAnalyzer

I've adapted it in a [project](https://github.com/hwoodiwiss/ArgumentativeFilters) of mine, and it works well.

**Comment by hwoodiwiss** [comment]
Also, I'd be interested in picking this up if it wouldn't be stepping on any toes.

**Comment by domn1995** [comment]
Please do! Feel free to reach out if you need any help 👍
