### ISSUE TITLE
Inner union compile with error `Cannot implicitly convert type 'X' to 'Y`

### ISSUE THREAD

**Issue by KarolBajkowski** [domn1995/dunet#50]
Hi. First of all, I'd like to thank you for this excellent library! It is very useful in many contexts! That is great and impressive work! :)

It would be nice if the inner union classes worked. Below is the example that doesn't compile
```
using Dunet;

Console.WriteLine("Hello, World!");

public class Foo
{
    [Union]
    public partial record R
    {
        public partial record O1();
    }

    public R Bar()
    {
        return new R.O1();
    }
}
```

The error says: `Error	CS0029	Cannot implicitly convert type 'Foo.R.O1' to 'Foo.R'`
Although below code works just fine:
```
using Dunet;

Console.WriteLine("Hello, World!");

[Union]
public partial record R
{
    public partial record O1();
}

public class Foo
{
    public R Bar()
    {
        return new R.O1();
    }
}
```

I would expect that both variants of code compile. The first version could be useful because the result type can be hidden inside the class. Is it possible to fix that?

**Comment by domn1995** [comment]
Thanks for filing this issue and for the kind words! This is certainly an interesting use case. I see the value in hiding a result type like that, so I think it makes sense to support it.

My only worry is the complexity of supporting arbitrary nesting, but handling one layer of nesting should be pretty straightforward.

**Comment by domn1995** [comment]
Just did some research on this. Due to source generators not being able to alter existing code, you'd have to make any parent classes of a union definition also partial. Using the OP as an example:

```cs
using Dunet;

Console.WriteLine("Hello, World!");

// The `partial` keyword is required to source generate correctly.
public partial class Foo
{
    [Union]
    public partial record R
    {
        public partial record O1();
    }

    public R Bar()
    {
        return new R.O1();
    }
}
```

This applies to arbitrarily deeply nested union definitions, all parent classes would have to be partial as well.

@KarolBajkowski do you feel like it's still worth pursuing this use case, knowing that it will force the partial modifier where it may not be intended in order to support it?

**Comment by KarolBajkowski** [comment]
Thank you for investigating that deeper! :) I can see now what's the issue here.

According to:
https://stackoverflow.com/questions/9143046/nested-partial-class
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

this code won't compile
```
Console.WriteLine("Hello, World!");

public class Foo
{
    public partial record R
    {
        public partial record O1();
    }
}
public class Foo
{
    public partial record R
    {
        public partial record O2();
    }
}
```

but this will
```
Console.WriteLine("Hello, World!");

public partial class Foo
{
    public partial record R
    {
        public partial record O1();
    }
}
public partial class Foo
{
    public partial record R
    {
        public partial record O2();
    }
}
```

Now I can see why nested partial classes require that the parent class also has to be partial.

I can see one scenario when nested unions can be useful. Although not everyone might agree about that idea, I think in teams with some degree of discipline keeping care about convention it might be a viable option. I used a similar pattern in f# code in my personal project and I think it isn't totally crazy :D

I'll try to compress the way of thinking but still include the essence of the idea.
Consider the following code:

```
[Union]
public partial record FooBarResult
{
    // some options...
}

[Union]
public partial record FooBazResult
{
    // some options...
}

public class Foo
{
    public FooBarResult Bar()
    {
        // some code, possibly hundreds of lines of codes ...
    }

   // some other methods
    
    public FooBazResult Baz()
    {
        // some code ...
    }
}
```

Here is an important assumption: I assume that `FooBazResult` will be relatively small and won't take more than 10-20 lines of code, typically maybe 5-10 lines. I assume that keeping `FooBazResult` in the same file as `Baz` method is an acceptable option.

The result type will usually need a more specific name to avoid ambiguity. I also attached `Foo` name to the name because in general, we could have multiple classes in the same namespace, so to avoid name collision I think `Foo` prefix is needed. This code could be OK for many developers, but I personally don't like this approach because there is a clear separation between methods and result types. When I read the definition of the `Baz` class I need to scroll possibly several screens up or search for a separate file to see the definition of `FooBazResult`. That isn't optimal. `Baz` and `FooBazResult` are very tightly coupled, but code could be placed in distinct places of the same file or even in totally separate files. That makes working on the `Baz` method harder without any clear advantages.

Let's imagine nested unions have been implemented.
```
public partial class Foo
{
    [Union]
    public partial record BarResult
    {
        public partial record O1();
    }

    public FooBarResult Bar()
    {
        // some code, possibly hundreds of lines of codes ...
    }

   // some other methods and nested result types
    
    [Union]
    public partial record BazResult
    {
        public partial record O1();
    }
    public FooBazResult Baz()
    {
        // some code ...
    }
}
```

The disadvantage of that approach is as you mentioned `Foo` has to be partial. It's a tradeoff. But in that scenario, I think it's worth accepting that tradeoff. Because in that scenario `BazResult` can be placed close to `Baz` and it makes sense since both 'objects' are tightly coupled. I think it's easier to read and easier to work with. Of course, it needs some discipline and relies solely on the convention and probably some specialized analyzer would help to keep that convention when needed (that's technically possible but I think no one would spend time on that, since effort would be quite high).

All in all, I think it's worth adding support for nested unions just to support the above scenario. Of course, it's my personal point of view, but I hope I'm not completely crazy after the explanation ;)

**Comment by domn1995** [comment]
Just put a PR for this. @KarolBajkowski would you mind looking through at least the test cases to make sure they address your needs? Thanks!

**Comment by domn1995** [comment]
@KarolBajkowski v1.2.0 now includes support for this use case. Thanks again for filing this issue and helping review it. Cheers!

**Comment by KarolBajkowski** [comment]
That's my pleasure :) Thank you so much for implementing that feature in such a rapid time period! 😃 🥇 If I find some other reasonable ideas for improvements I'll come back here if you don't mind ;) Take care! 🍻
